
/* ReachingDefsIRInterface.hpp
   NOTE: This file was automatically generated by DFAGen.  It is the IR
         interface for the ReachingDefs analysis.
*/

#ifndef ReachingDefsIRInterface_H
#define ReachingDefsIRInterface_H

#include <iostream>
#include <list>
#include <string>
#include <OpenAnalysis/ExprTree/ExprTree.hpp>
#include <OpenAnalysis/Utils/OA_ptr.hpp>
#include <OpenAnalysis/IRInterface/IRHandles.hpp>

namespace OA {
  namespace ReachingDefs {

class ReachingDefsIRInterface : public virtual IRHandlesIRInterface {
  public:
    ReachingDefsIRInterface() { }
    virtual ~ReachingDefsIRInterface() { }

    virtual OA_ptr<IRStmtIterator> getStmtIterator(ProcHandle h) = 0;

    virtual OA_ptr<MemRefHandleIterator> getAllMemRefs(StmtHandle stmt) = 0;

    virtual OA_ptr<MemRefHandleIterator> getDefMemRefs(StmtHandle stmt) = 0;

    virtual OA_ptr<MemRefHandleIterator> getUseMemRefs(StmtHandle stmt) = 0;

    virtual OA_ptr<IRCallsiteIterator> getCallsites(StmtHandle h) = 0;

    virtual OA_ptr<OA::ExprHandleIterator>
        getExprHandleIterator(OA::StmtHandle stmt) = 0;

    virtual OA_ptr<ExprTree> getExprTree(OA::ExprHandle h) = 0;
};

  } // end of namespace ReachingDefs
} // end of namespace OA

#endif
