geneInits <- list(mustar.rstar = cbind(c(0, -2, 2), c(0, 1, 1)),
                  ss = c(rep(1, 720), rep(2, 40), rep(3, 40)),
                  r  = c(rep(0, 720), rep(1, 80)),
                  p0 = 0.8,
                  p0.lb = 0.2,
                  p0.ub = 0.99999,
                  alpha = 2,
                  beta  = 2,
                  sigmaSsquare = 1,
                  as = 2,
                  bs = 1,
                  b  = 0.0,
                  sigmaBsquare  = 1,
                  ab = 1,
                  bb = 0.2,
                  b1 = 1.0,
                  sigmaBsquare1 = 1,
                  ab1 = 1,
                  bb1 = 0.2,
                  b0 = 0,
                  b1.1 = 1.0,
                  sigmaCsquare = 16,
                  M = 1,
                  am = 2,
                  bm = 0.5)

geneInits
