#!/bin/sh
# -*-Mode: sh;-*-

# $Header: /Volumes/cvsrep/developer/OpenADFortTk/autogen,v 1.1 2005/08/29 17:09:31 eraxxon Exp $

## **************************************************************************
##
## File: 
##    Regenerate 'configure' and 'Makefile.ins'
##
## Author:
##    Written by Nathan Tallent, Rice University.
##    
## **************************************************************************

aclocal
#libtoolize -f -c
automake -a -f -c
aclocal && autoconf && automake

#############################################################################
