/* LivenessBV.cpp
   NOTE: This file was automatically generated by DFAGen.  It is the
         implementation of the class for LivenessBV analysis results.
*/


#include "auto_LivenessBV.hpp"

namespace OA {
  namespace LivenessBV {


OA_ptr<DataFlow::DFSetBitImplIterator<Alias::AliasTag > > LivenessBV::getLivenessBVIterator(StmtHandle s) const {
    OA_ptr<DataFlow::DFSetBitImplIterator<Alias::AliasTag > > retval;

    if(mLivenessBV.find(s) == mLivenessBV.end()) {
        retval = new DataFlow::DFSetBitImplIterator<Alias::AliasTag > ();
    } else {
        retval = new DataFlow::DFSetBitImplIterator<Alias::AliasTag > (
            mLivenessBV.find(s)->second);
    }

    return retval;
}


OA_ptr<DataFlow::DFSetBitImplIterator<Alias::AliasTag > > LivenessBV::getExitLivenessBVIterator() const {
    OA_ptr<DataFlow::DFSetBitImplIterator<Alias::AliasTag > > retval;

    retval = new DataFlow::DFSetBitImplIterator<Alias::AliasTag > (mExitLivenessBV);
    return retval;
}


void LivenessBV::output(IRHandlesIRInterface& ir) const {
    sOutBuild->objStart("LivenessBV");

    sOutBuild->mapStart("mLivenessBV", "StmtHandle", "OA_ptr<LivenessBVDFSet>");

    std::map<StmtHandle,OA_ptr<LivenessBVDFSet> >::const_iterator mapIter;
    for (mapIter = mLivenessBV.begin(); mapIter != mLivenessBV.end(); mapIter++) {
        StmtHandle s = mapIter->first;
        OA_ptr<LivenessBVDFSet> rdset = mapIter->second;
        if ( rdset.ptrEqual(0) ) continue;

        sOutBuild->mapEntryStart();
        sOutBuild->mapKeyStart();
        sOutBuild->outputIRHandle(s, ir);
        sOutBuild->mapKeyEnd();
        sOutBuild->mapValueStart();


        sOutBuild->listStart();
        OA_ptr<DataFlow::DFSetBitImplIterator<Alias::AliasTag > > setIter;
        setIter = getLivenessBVIterator(s);
        for ( ; setIter->isValid(); (*setIter)++ ) {
             sOutBuild->listItemStart();
             setIter->current().output(ir);
             sOutBuild->listItemEnd();
        }
        sOutBuild->listEnd();
        sOutBuild->mapValueEnd();
        sOutBuild->mapEntryEnd();
    }
    sOutBuild->mapEnd("mLivenessBV");
    sOutBuild->objEnd("LivenessBV");
}


void LivenessBV::dump(
    std::ostream& os,
    OA_ptr<IRHandlesIRInterface> ir,
    Alias::Interface& aliasResults) const
{
    os << "LivenessBV Analysis results." << endl;
    std::map<StmtHandle, OA_ptr<LivenessBVDFSet> >::const_iterator mapIter;

    for (mapIter = mLivenessBV.begin(); mapIter != mLivenessBV.end(); mapIter++) {
        os << "\tstmt = " << ir->toString(mapIter->first) << std::endl;
        OA_ptr<DataFlow::DFSetBitImplIterator<Alias::AliasTag > > iter;
        iter = getLivenessBVIterator(mapIter->first);

        for ( ; iter->isValid(); (*iter)++) {
            os << "\t\t";
        iter->current().dump(os, *mIR, aliasResults);
            os << std::endl;
        }
    }
}


  } // end of LivenessBV namespace
} // end of OA namespace
