/* Vary.cpp
   NOTE: This file was automatically generated by DFAGen.  It is the
         implementation of the class for Vary analysis results.
*/


#include "auto_Vary.hpp"

namespace OA {
  namespace Vary {


OA_ptr<DataFlow::DataFlowSetImplIterator<Alias::AliasTag > > Vary::getVaryIterator(StmtHandle s) const {
    OA_ptr<DataFlow::DataFlowSetImplIterator<Alias::AliasTag > > retval;

    if(mVary.find(s) == mVary.end()) {
        retval = new DataFlow::DataFlowSetImplIterator<Alias::AliasTag > ();
    } else {
        retval = new DataFlow::DataFlowSetImplIterator<Alias::AliasTag > (
            mVary.find(s)->second);
    }

    return retval;
}


OA_ptr<DataFlow::DataFlowSetImplIterator<Alias::AliasTag > > Vary::getExitVaryIterator() const {
    OA_ptr<DataFlow::DataFlowSetImplIterator<Alias::AliasTag > > retval;

    retval = new DataFlow::DataFlowSetImplIterator<Alias::AliasTag > (mExitVary);
    return retval;
}


void Vary::output(IRHandlesIRInterface& ir) const {
    sOutBuild->objStart("Vary");

    sOutBuild->mapStart("mVary", "StmtHandle", "OA_ptr<VaryDFSet>");

    std::map<StmtHandle,OA_ptr<VaryDFSet> >::const_iterator mapIter;
    for (mapIter = mVary.begin(); mapIter != mVary.end(); mapIter++) {
        StmtHandle s = mapIter->first;
        OA_ptr<VaryDFSet> rdset = mapIter->second;
        if ( rdset.ptrEqual(0) ) continue;

        sOutBuild->mapEntryStart();
        sOutBuild->mapKeyStart();
        sOutBuild->outputIRHandle(s, ir);
        sOutBuild->mapKeyEnd();
        sOutBuild->mapValueStart();


        sOutBuild->listStart();
        OA_ptr<DataFlow::DataFlowSetImplIterator<Alias::AliasTag > > setIter;
        setIter = getVaryIterator(s);
        for ( ; setIter->isValid(); (*setIter)++ ) {
             sOutBuild->listItemStart();
             setIter->current().output(ir);
             sOutBuild->listItemEnd();
        }
        sOutBuild->listEnd();
        sOutBuild->mapValueEnd();
        sOutBuild->mapEntryEnd();
    }
    sOutBuild->mapEnd("mVary");
    sOutBuild->objEnd("Vary");
}


void Vary::dump(
    std::ostream& os,
    OA_ptr<IRHandlesIRInterface> ir,
    Alias::Interface& aliasResults) const
{
    os << "Vary Analysis results." << endl;
    std::map<StmtHandle, OA_ptr<VaryDFSet> >::const_iterator mapIter;

    for (mapIter = mVary.begin(); mapIter != mVary.end(); mapIter++) {
        os << "\tstmt = " << ir->toString(mapIter->first) << std::endl;
        OA_ptr<DataFlow::DataFlowSetImplIterator<Alias::AliasTag > > iter;
        iter = getVaryIterator(mapIter->first);

        for ( ; iter->isValid(); (*iter)++) {
            os << "\t\t";
        iter->current().dump(os, *mIR, aliasResults);
            os << std::endl;
        }
    }
}


  } // end of Vary namespace
} // end of OA namespace
