/* Copyright (c) 2003 John Garvin
 *
 * Preliminary version v06, July 11, 2003 
 *
 * get_name maps R internal function table indices to R function names.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
 */


#include <IOStuff.h>
#include <Parse.h>
#include <Defn.h>       /* includes Internals.h, which defines do_ functions */
#include <main/arithmetic.h>
#include <R_ext/RConverters.h>
#include <config.h>     /* OS #defines */
#include "get_name.h"

/* #define Unix 1 */

struct map {
  char *name;
  CCODE cfun;
};

static const struct map name_map[] = 
{
  {"do_if", do_if},
  {"do_while", do_while},
  {"do_for", do_for},
  {"do_repeat", do_repeat},
  {"do_break", do_break},
  {"do_break", do_break},
  {"do_return", do_return},
  {"do_stop", do_stop},
  {"do_warning", do_warning},
#ifdef NEW_CONDITION_HANDLING
  {"do_addCondHands", do_addCondHands},
  {"do_resetCondHands", do_resetCondHands},
  {"do_signalCondition", do_signalCondition},
  {"do_dfltStop", do_dfltStop},
  {"do_dfltWarn", do_dfltWarn},
  {"do_addRestart", do_addRestart},
  {"do_getRestart", do_getRestart},
  {"do_invokeRestart", do_invokeRestart},
#endif
  {"do_addTryHandlers", do_addTryHandlers},
  {"do_geterrmessage", do_geterrmessage},
  {"do_restart", do_restart},
  {"do_function", do_function},
  {"do_asfunction", do_asfunction},
  {"do_set", do_set},
  {"do_set", do_set},
  {"do_set", do_set},
  {"do_begin", do_begin},
  {"do_paren", do_paren},
  {"do_subset_dflt", do_subset_dflt},
  {"do_subset2_dflt", do_subset2_dflt},
  {"do_subset", do_subset},
  {"do_subset2", do_subset2},
  {"do_subset3", do_subset3},
  {"do_AT", do_AT},
  {"do_subassign", do_subassign},
  {"do_subassign2", do_subassign2},
  {"do_subassign3", do_subassign3},
  {"do_switch", do_switch},
  {"do_browser", do_browser},
  {"do_debug", do_debug},
  {"do_debug", do_debug},
  {"do_trace", do_trace},
  {"do_trace", do_trace},
  {"do_internal", do_internal},
  {"do_onexit", do_onexit},
  {"do_recall", do_recall},
  {"do_delay", do_delay},
  {"do_primitive", do_primitive},
  {"do_ident", do_ident},
  {"do_arith", do_arith},
  {"do_arith", do_arith},
  {"do_arith", do_arith},
  {"do_arith", do_arith},
  {"do_arith", do_arith},
  {"do_arith", do_arith},
  {"do_arith", do_arith},
  {"do_matprod", do_matprod},
  {"do_matprod", do_matprod},
  {"do_relop", do_relop},
  {"do_relop", do_relop},
  {"do_relop", do_relop},
  {"do_relop", do_relop},
  {"do_relop", do_relop},
  {"do_relop", do_relop},
  {"do_logic", do_logic},
  {"do_logic", do_logic},
  {"do_logic", do_logic},
  {"do_logic2", do_logic2},
  {"do_logic2", do_logic2},
  {"do_seq", do_seq},
  {"do_tilde", do_tilde},
  {"do_logic3", do_logic3},
  {"do_logic3", do_logic3},
  {"do_makevector", do_makevector},
  {"do_complex", do_complex},
  {"do_matrix", do_matrix},
  {"do_length", do_length},
  {"do_lengthgets", do_lengthgets},
  {"do_rowscols", do_rowscols},
  {"do_rowscols", do_rowscols},
  {"do_c", do_c},
  {"do_unlist", do_unlist},
  {"do_bind", do_bind},
  {"do_bind", do_bind},
  {"do_drop", do_drop},
  {"do_class", do_class},
  {"do_classgets", do_classgets},
  {"R_do_data_class", R_do_data_class},
  {"R_do_set_class", R_do_set_class},
  {"do_unclass", do_unclass},
  {"do_names", do_names},
  {"do_namesgets", do_namesgets},
  {"do_dimnames", do_dimnames},
  {"do_dimnamesgets", do_dimnamesgets},
  {"do_allnames", do_allnames},
  {"do_dim", do_dim},
  {"do_dimgets", do_dimgets},
  {"do_attributes", do_attributes},
  {"do_attributesgets", do_attributesgets},
  {"do_attr", do_attr},
  {"do_attrgets", do_attrgets},
  {"do_comment", do_comment},
  {"do_commentgets", do_commentgets},
  {"do_get", do_get},
  {"do_mget", do_mget},
  {"do_get", do_get},
  {"do_assign", do_assign},
  {"do_remove", do_remove},
  {"do_duplicated", do_duplicated},
  {"do_duplicated", do_duplicated},
  {"do_first_min", do_first_min},
  {"do_first_max", do_first_max},
  {"do_match", do_match},
  {"do_pmatch", do_pmatch},
  {"do_charmatch", do_charmatch},
  {"do_matchcall", do_matchcall},
  {"do_compcases", do_compcases},
  {"do_attach", do_attach},
  {"do_detach", do_detach},
  {"do_search", do_search},
  {"do_Math2", do_Math2},
  {"do_atan", do_atan},
  {"do_log", do_log},
  {"do_Math2", do_Math2},
  {"do_abs", do_abs},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math1", do_math1},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_math2", do_math2},
  {"do_cmathfuns", do_cmathfuns},
  {"do_cmathfuns", do_cmathfuns},
  {"do_cmathfuns", do_cmathfuns},
  {"do_cmathfuns", do_cmathfuns},
  {"do_cmathfuns", do_cmathfuns},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math3", do_math3},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_math4", do_math4},
  {"do_random1", do_random1},
  {"do_random1", do_random1},
  {"do_random1", do_random1},
  {"do_random1", do_random1},
  {"do_random1", do_random1},
  {"do_random1", do_random1},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random2", do_random2},
  {"do_random3", do_random3},
  {"do_rmultinom", do_rmultinom},
  {"do_sample", do_sample},
  {"do_RNGkind", do_RNGkind},
  {"do_setseed", do_setseed},
  {"do_summary", do_summary},
  {"do_summary", do_summary},
  {"do_summary", do_summary},
  {"do_summary", do_summary},
  {"do_range", do_range},
  {"do_cov", do_cov},
  {"do_cov", do_cov},
  {"do_cum", do_cum},
  {"do_cum", do_cum},
  {"do_cum", do_cum},
  {"do_cum", do_cum},
  {"do_ascharacter", do_ascharacter},
  {"do_asvector", do_asvector},
  {"do_paste", do_paste},
  {"do_format", do_format},
  {"do_formatinfo", do_formatinfo},
  {"do_cat", do_cat},
  {"do_call", do_call},
  {"do_docall", do_docall},
  {"do_ascall", do_ascall},
  {"do_typecvt", do_typecvt},
  {"do_as_environment", do_as_environment},
  {"do_nchar", do_nchar},
  {"do_substr", do_substr},
  {"do_substrgets", do_substrgets},
  {"do_strsplit", do_strsplit},
  {"do_abbrev", do_abbrev},
  {"do_makenames", do_makenames},
  {"do_grep", do_grep},
  {"do_gsub", do_gsub},
  {"do_gsub", do_gsub},
  {"do_regexpr", do_regexpr},
  {"do_pgrep", do_pgrep},
  {"do_pgsub", do_pgsub},
  {"do_pgsub", do_pgsub},
  {"do_pregexpr", do_pregexpr},
  {"do_agrep", do_agrep},
  {"do_tolower", do_tolower},
  {"do_toupper", do_toupper},
  {"do_chartr", do_chartr},
  {"do_sprintf", do_sprintf},
  {"do_makeunique", do_makeunique},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_is", do_is},
  {"do_isvector", do_isvector},
  {"do_isna", do_isna},
  {"do_isnan", do_isnan},
  {"do_isfinite", do_isfinite},
  {"do_isinfinite", do_isinfinite},
  {"do_proctime", do_proctime},
  {"do_gctime", do_gctime},
  {"do_version", do_version},
  {"do_machine", do_machine},
  {"do_commandArgs", do_commandArgs},
  {"do_int_unzip", do_int_unzip},
#ifdef Win32
  {"do_system", do_system},
#else
  {"do_system", do_system},
#endif
#ifdef Win32
  {"do_unlink", do_unlink},
  {"do_helpstart", do_helpstart},
  {"do_helpitem", do_helpitem},
  {"do_flushconsole", do_flushconsole},
  {"do_winver", do_winver},
  {"do_saveDevga", do_saveDevga},
  {"do_shellexec", do_shellexec},
  {"do_windialog", do_windialog},
  {"do_windialogstring", do_windialogstring},
  {"do_winmenunames", do_winmenunames},
  {"do_wingetmenuitems", do_wingetmenuitems},
  {"do_winmenuadd", do_winmenuadd},
  {"do_winmenudel", do_winmenudel},
  {"do_memsize", do_memsize},
  {"do_dllversion", do_dllversion},
  {"do_bringtotop", do_bringtotop},
  {"do_selectlist", do_selectlist},
  {"do_readClipboard", do_readClipboard},
  {"do_writeClipboard", do_writeClipboard},
  {"do_chooseFiles", do_chooseFiles},
#endif
#if defined(__APPLE_CC__) && defined(HAVE_AQUA)
  {"do_wsbrowser", do_wsbrowser},
  {"do_browsepkgs", do_browsepkgs},
  {"do_datamanger", do_datamanger},
  {"do_packagemanger", do_packagemanger},
  {"do_flushconsole", do_flushconsole},
  {"do_hsbrowser", do_hsbrowser},
#endif
  {"do_parse", do_parse},
  {"do_save", do_save},
  {"do_saveToConn", do_saveToConn},
  {"do_load", do_load},
  {"do_loadFromConn", do_loadFromConn},
  {"do_serializeToConn", do_serializeToConn},
  {"do_unserializeFromConn", do_unserializeFromConn},
  {"do_deparse", do_deparse},
  {"do_dput", do_dput},
  {"do_dump", do_dump},
  {"do_substitute", do_substitute},
  {"do_quote", do_quote},
  {"do_quit", do_quit},
  {"do_interactive", do_interactive},
  {"do_readln", do_readln},
  {"do_menu", do_menu},
  {"do_printdefault", do_printdefault},
  {"do_prmatrix", do_prmatrix},
  {"do_invisible", do_invisible},
  {"do_gc", do_gc},
  {"do_gcinfo", do_gcinfo},
  {"do_gctorture", do_gctorture},
  {"do_memoryprofile", do_memoryprofile},
  {"do_rep", do_rep},
  {"do_makelist", do_makelist},
  {"do_split", do_split},
  {"do_symbol", do_symbol},
  {"do_symbol", do_symbol},
  {"do_isloaded", do_isloaded},
  {"do_dotCode", do_dotCode},
  {"do_dotCode", do_dotCode},
  {"do_External", do_External},
  {"do_dotcall", do_dotcall},
  {"do_Externalgr", do_Externalgr},
  {"do_dotcallgr", do_dotcallgr},
  {"do_dynload", do_dynload},
  {"do_dynunload", do_dynunload},
  {"do_ls", do_ls},
  {"do_typeof", do_typeof},
  {"do_eval", do_eval},
  {"do_eval", do_eval},
  {"do_expression", do_expression},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_sys", do_sys},
  {"do_parentframe", do_parentframe},
  {"do_sort", do_sort},
  {"do_isunsorted", do_isunsorted},
  {"do_psort", do_psort},
  {"do_qsort", do_qsort},
  {"do_radixsort", do_radixsort},
  {"do_order", do_order},
  {"do_rank", do_rank},
  {"do_missing", do_missing},
  {"do_nargs", do_nargs},
  {"do_scan", do_scan},
  {"do_countfields", do_countfields},
  {"do_readtablehead", do_readtablehead},
  {"do_transpose", do_transpose},
  {"do_aperm", do_aperm},
  {"do_builtins", do_builtins},
  {"do_edit", do_edit},
  {"do_dataentry", do_dataentry},
  {"do_args", do_args},
  {"do_formals", do_formals},
  {"do_body", do_body},
  {"do_bodyCode", do_bodyCode},
  {"do_globalenv", do_globalenv},
  {"do_envir", do_envir},
  {"do_envirgets", do_envirgets},
  {"do_env2list", do_env2list},
  {"do_regFinaliz", do_regFinaliz},
  {"do_options", do_options},
  {"do_sink", do_sink},
  {"do_sinknumber", do_sinknumber},
  {"do_libfixup", do_libfixup},
  {"do_pos2env", do_pos2env},
  {"do_lapply", do_lapply},
  {"do_apply", do_apply},
  {"do_colsum", do_colsum},
  {"do_colsum", do_colsum},
  {"do_colsum", do_colsum},
  {"do_colsum", do_colsum},
  {"do_Rprof", do_Rprof},
  {"do_objectsize", do_objectsize},
  {"do_memlimits", do_memlimits},
  {"do_merge", do_merge},
  {"do_capabilities", do_capabilities},
  {"do_newenv", do_newenv},
  {"do_parentenv", do_parentenv},
  {"do_parentenvgets", do_parentenvgets},
#if 0
  {"do_visibleflag", do_visibleflag},
#endif
  {"do_fileshow", do_fileshow},
  {"do_filecreate", do_filecreate},
  {"do_fileremove", do_fileremove},
  {"do_filerename", do_filerename},
  {"do_fileappend", do_fileappend},
  {"do_filesymlink", do_filesymlink},
  {"do_listfiles", do_listfiles},
  {"do_fileexists", do_fileexists},
  {"do_filechoose", do_filechoose},
  {"do_fileinfo", do_fileinfo},
  {"do_fileaccess", do_fileaccess},
  {"do_dircreate", do_dircreate},
  {"do_tempfile", do_tempfile},
  {"do_tempdir", do_tempdir},
  {"do_Rhome", do_Rhome},
  {"do_date", do_date},
  {"do_indexsearch", do_indexsearch},
  {"do_getenv", do_getenv},
  {"do_putenv", do_putenv},
  {"do_getwd", do_getwd},
  {"do_setwd", do_setwd},
  {"do_basename", do_basename},
  {"do_dirname", do_dirname},
  {"do_sysinfo", do_sysinfo},
  {"do_syssleep", do_syssleep},
  {"do_getlocale", do_getlocale},
  {"do_setlocale", do_setlocale},
  {"do_localeconv", do_localeconv},
  {"do_pathexpand", do_pathexpand},
  {"do_sysgetpid", do_sysgetpid},
  {"do_fft", do_fft},
  {"do_mvfft", do_mvfft},
  {"do_nextn", do_nextn},
  {"do_polyroot", do_polyroot},
  {"do_PS", do_PS},
  {"do_PicTeX", do_PicTeX},
  {"do_XFig", do_XFig},
  {"do_PDF", do_PDF},
#ifdef Win32
  {"do_devga", do_devga},
#endif
#ifdef Unix
  {"do_X11", do_X11},
  {"do_Gnome", do_Gnome},
  {"do_GTK", do_GTK},
  {"do_Quartz", do_Quartz},
#endif
  {"do_devcontrol", do_devcontrol},
  {"do_devcopy", do_devcopy},
  {"do_devcur", do_devcur},
  /*  {"do_device", do_device}, */
  {"do_devnext", do_devnext},
  {"do_devoff", do_devoff},
  {"do_devprev", do_devprev},
  {"do_devset", do_devset},
  {"do_rgb", do_rgb},
  {"do_rgb", do_rgb},
  {"do_RGB2hsv", do_RGB2hsv},
  {"do_hsv", do_hsv},
  {"do_gray", do_gray},
  {"do_colors", do_colors},
  {"do_col2RGB", do_col2RGB},
  {"do_palette", do_palette},
  {"do_plot_new", do_plot_new},
  {"do_plot_window", do_plot_window},
  {"do_axis", do_axis},
  {"do_plot_xy", do_plot_xy},
  {"do_text", do_text},
  {"do_mtext", do_mtext},
  {"do_title", do_title},
  {"do_abline", do_abline},
  {"do_box", do_box},
  {"do_rect", do_rect},
  {"do_polygon", do_polygon},
  {"do_par", do_par},
  {"do_readonlypars", do_readonlypars},
  {"do_segments", do_segments},
  {"do_arrows", do_arrows},
  {"do_layout", do_layout},
  {"do_locator", do_locator},
  {"do_identify", do_identify},
  {"do_strheight", do_strheight},
  {"do_strwidth", do_strwidth},
  {"do_contour", do_contour},
  {"do_contourLines", do_contourLines},
  {"do_image", do_image},
  {"do_dend", do_dend},
  {"do_dendwindow", do_dendwindow},
  {"do_replay", do_replay},
  {"do_erase", do_erase},
  {"do_persp", do_persp},
  {"do_filledcontour", do_filledcontour},
  /*  {"do_getGPar", do_getGPar}, */
  {"do_playDL", do_playDL},
  {"do_setGPar", do_setGPar},
  {"do_getSnapshot", do_getSnapshot},
  {"do_playSnapshot", do_playSnapshot},
  {"do_symbols", do_symbols},
  {"do_inherits", do_inherits},
  {"do_usemethod", do_usemethod},
  {"do_nextmethod", do_nextmethod},
  {"do_standardGeneric", do_standardGeneric},
  {"do_nlm", do_nlm},
  {"do_fmin", do_fmin},
  {"do_zeroin", do_zeroin},
  {"do_optim", do_optim},
  {"do_optimhess", do_optimhess},
  {"do_termsform", do_termsform},
  {"do_updateform", do_updateform},
  {"do_modelframe", do_modelframe},
  {"do_modelmatrix", do_modelmatrix},
  {"do_D", do_D},
  {"do_deriv", do_deriv},
  {"do_loadhistory", do_loadhistory},
  {"do_savehistory", do_savehistory},
  {"do_systime", do_systime},
  {"do_asPOSIXct", do_asPOSIXct},
  {"do_asPOSIXlt", do_asPOSIXlt},
  {"do_formatPOSIXlt", do_formatPOSIXlt},
  {"do_strptime", do_strptime},
  {"do_D2POSIXlt", do_D2POSIXlt},
  {"do_POSIXlt2D", do_POSIXlt2D},
#ifdef BYTECODE
  {"do_mkcode", do_mkcode},
  {"do_bcclose", do_bcclose},
  {"do_is_builtin_internal", do_is_builtin_internal},
  {"do_disassemble", do_disassemble},
  {"do_bcversion", do_bcversion},
  {"do_loadfile", do_loadfile},
  {"do_savefile", do_savefile},
  {"do_putconst", do_putconst},
#endif
  {"do_stdin", do_stdin},
  {"do_stdout", do_stdout},
  {"do_stderr", do_stderr},
  {"do_readLines", do_readLines},
  {"do_writelines", do_writelines},
  {"do_readbin", do_readbin},
  {"do_writebin", do_writebin},
  {"do_readchar", do_readchar},
  {"do_writechar", do_writechar},
  {"do_open", do_open},
  {"do_isopen", do_isopen},
  {"do_isincomplete", do_isincomplete},
  {"do_isseekable", do_isseekable},
  {"do_close", do_close},
  {"do_flush", do_flush},
  {"do_url", do_url},
  {"do_url", do_url},
  {"do_pipe", do_pipe},
  {"do_fifo", do_fifo},
  {"do_gzfile", do_gzfile},
  {"do_unz", do_unz},
  {"do_bzfile", do_bzfile},
  {"do_seek", do_seek},
  {"do_truncate", do_truncate},
  {"do_pushback", do_pushback},
  {"do_pushbacklength", do_pushbacklength},
  {"do_textconnection", do_textconnection},
  {"do_sockconn", do_sockconn},
  {"do_sockselect", do_sockselect},
  {"do_getallconnections", do_getallconnections},
  {"do_sumconnection", do_sumconnection},
  {"do_download", do_download},
  {"do_nsl", do_nsl},
  {"do_gzcon", do_gzcon},
  {"do_readDCF", do_readDCF},
  {"do_getNumRtoCConverters", do_getNumRtoCConverters},
  {"do_getRtoCConverterDescriptions", do_getRtoCConverterDescriptions},
  {"do_getRtoCConverterStatus", do_getRtoCConverterStatus},
  {"do_setToCConverterActiveStatus", do_setToCConverterActiveStatus},
  {"do_setToCConverterActiveStatus", do_setToCConverterActiveStatus},
  {"do_lockEnv", do_lockEnv},
  {"do_envIsLocked", do_envIsLocked},
  {"do_lockBnd", do_lockBnd},
  {"do_lockBnd", do_lockBnd},
  {"do_bndIsLocked", do_bndIsLocked},
  {"do_mkActiveBnd", do_mkActiveBnd},
  {"do_bndIsActive", do_bndIsActive},
  {"do_mkUnbound", do_mkUnbound},
  {"do_isNSEnv", do_isNSEnv},
  {"do_regNS", do_regNS},
  {"do_unregNS", do_unregNS},
  {"do_getRegNS", do_getRegNS},
  {"do_getNSRegistry", do_getNSRegistry},
  {"do_importIntoEnv", do_importIntoEnv}
};

static int first_time = 1;
static int num_names;
static char **fn_names;

void
init_name_map(void)
{
  int i, j;
  int missing = 0;

  for (num_names = 0; R_FunTab[num_names].name != NULL; num_names++)
    ;
  fn_names = (char **)malloc (sizeof (char *) * num_names);
  if (fn_names == NULL) {
    fprintf (stderr, "init_name_map: Error: unable to allocate space for %d names\n", num_names);
    exit (1);
  }

  for (i = 0; i < num_names; i++) {
    fn_names[i] = NULL;
    for (j = 0; j < sizeof(name_map)/sizeof(name_map[0]); j++)
      if (name_map[j].cfun == R_FunTab[i].cfun) {
        fn_names[i] = name_map[j].name;
        break;
      }
    if (fn_names[i] == NULL) {
      fprintf (stderr, "init_name_map: Error: unable to find name for table entry %d (\"%s\", 0x%x)\n", i, R_FunTab[i].name, R_FunTab[i].cfun);
      missing++;
    }
  }
  if (missing > 0) {
      fprintf (stderr, "init_name_map: Unable to find names for %d functions. Aborting.\n", missing);
      exit (0);
  }
}

const char *get_name(int n) {
  if (first_time) {
    init_name_map ();
    first_time = 0;
  }
  if (n >= 0 && n < num_names)
    return fn_names[n];
  else {
    fprintf (stderr, "get_name: Illegal name index (%d)\n", n);
    return ("illegal_name");
  }
}

