/* Copyright (c) 2003 John Garvin
 *
 * Preliminary version v06, July 11, 2003 
 *
 * get_name maps R internal function table indices to R function names.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
 */


#include <IOStuff.h>
#include <Parse.h>
#include <Defn.h>
#include <arithmetic.h>
#include <R_ext/RConverters.h>
#include "get_name.h"

struct map {
  char *name;
  CCODE cfun;
};

static const struct map name_map[] = 
{
  { "R_do_data_class", R_do_data_class },
  { "R_do_set_class", R_do_set_class },
  { "do_AT", do_AT },
  { "do_D", do_D },
  { "do_D2POSIXlt",do_D2POSIXlt },
  { "do_External", do_External },
  { "do_Externalgr", do_Externalgr },
  { "do_GTK", do_GTK },
  { "do_Gnome", do_Gnome },
  { "do_Math2",do_Math2 },
  { "do_PDF", do_PDF },
  { "do_POSIXlt2D",do_POSIXlt2D },
  { "do_PS", do_PS },
  { "do_PicTeX", do_PicTeX },
  { "do_Quartz", do_Quartz },
  { "do_RGB2hsv",do_RGB2hsv },
  { "do_RNGkind", do_RNGkind },
  { "do_Rhome", do_Rhome },
  { "do_Rprof", do_Rprof },
  { "do_X11", do_X11 },
  { "do_XFig", do_XFig },
  { "do_abbrev", do_abbrev },
  { "do_abline", do_abline },
  { "do_abs", do_abs },
  { "do_addCondHands",do_addCondHands },
  { "do_addRestart",do_addRestart },
  { "do_addTryHandlers",do_addTryHandlers },
  { "do_agrep", do_agrep },
  { "do_allnames", do_allnames },
  { "do_aperm", do_aperm },
  { "do_apply", do_apply },
  { "do_args", do_args },
  { "do_arith", do_arith },
  { "do_arrows", do_arrows },
  { "do_asPOSIXct", do_asPOSIXct },
  { "do_asPOSIXlt", do_asPOSIXlt },
  { "do_as_environment", do_as_environment },
  { "do_ascall", do_ascall },
  { "do_ascharacter", do_ascharacter },
  { "do_asfunction", do_asfunction },
  { "do_assign", do_assign },
  { "do_asvector", do_asvector },
  { "do_atan", do_atan },
  { "do_attach", do_attach },
  { "do_attr", do_attr },
  { "do_attrgets", do_attrgets },
  { "do_attributes", do_attributes },
  { "do_attributesgets", do_attributesgets },
  { "do_axis", do_axis },
  { "do_basename", do_basename },
  { "do_begin", do_begin },
  { "do_bind", do_bind },
  { "do_bndIsActive", do_bndIsActive },
  { "do_bndIsLocked", do_bndIsLocked },
  { "do_body", do_body },
  { "do_bodyCode",do_bodyCode },
  { "do_box", do_box },
  { "do_break", do_break },
  { "do_browser", do_browser },
  { "do_builtins", do_builtins },
  { "do_bzfile", do_bzfile },
  { "do_c", do_c },
  { "do_call", do_call },
  { "do_capabilities", do_capabilities },
  { "do_cat", do_cat },
  { "do_charmatch", do_charmatch },
  { "do_chartr", do_chartr },
  { "do_class", do_class },
  { "do_classgets", do_classgets },
  { "do_close", do_close },
  { "do_cmathfuns", do_cmathfuns },
  { "do_col2RGB", do_col2RGB },
  { "do_colors", do_colors },
  { "do_colsum", do_colsum },
  { "do_commandArgs", do_commandArgs },
  { "do_comment", do_comment },
  { "do_commentgets", do_commentgets },
  { "do_compcases", do_compcases },
  { "do_complex", do_complex },
  { "do_contour", do_contour },
  { "do_contourLines",do_contourLines },
  { "do_countfields", do_countfields },
  { "do_cov", do_cov },
  { "do_cum", do_cum },
  { "do_dataentry", do_dataentry },
  { "do_date", do_date },
  { "do_debug", do_debug },
  { "do_delay", do_delay },
  { "do_dend", do_dend },
  { "do_dendwindow", do_dendwindow },
  { "do_deparse", do_deparse },
  { "do_deriv", do_deriv },
  { "do_detach", do_detach },
  { "do_devcontrol", do_devcontrol },
  { "do_devcopy", do_devcopy },
  { "do_devcur", do_devcur },
  { "do_devnext", do_devnext },
  { "do_devoff", do_devoff },
  { "do_devprev", do_devprev },
  { "do_devset", do_devset },
  { "do_dfltStop",do_dfltStop },
  { "do_dfltWarn",do_dfltWarn },
  { "do_dim", do_dim },
  { "do_dimgets", do_dimgets },
  { "do_dimnames", do_dimnames },
  { "do_dimnamesgets", do_dimnamesgets },
  { "do_dircreate",do_dircreate },
  { "do_dirname", do_dirname },
  { "do_docall", do_docall },
  { "do_dotCode", do_dotCode },
  { "do_dotcall", do_dotcall },
  { "do_dotcallgr", do_dotcallgr },
  { "do_download", do_download },
  { "do_dput", do_dput },
  { "do_drop", do_drop },
  { "do_dump", do_dump },
  { "do_duplicated", do_duplicated },
  { "do_dynload", do_dynload },
  { "do_dynunload", do_dynunload },
  { "do_edit", do_edit },
  { "do_env2list",do_env2list },
  { "do_envIsLocked", do_envIsLocked },
  { "do_envir", do_envir },
  { "do_envirgets", do_envirgets },
  { "do_erase", do_erase },
  { "do_eval", do_eval },
  { "do_expression", do_expression },
  { "do_fft", do_fft },
  { "do_fifo", do_fifo },
  { "do_fileaccess", do_fileaccess },
  { "do_fileappend", do_fileappend },
  { "do_filechoose", do_filechoose },
  { "do_filecreate", do_filecreate },
  { "do_fileexists", do_fileexists },
  { "do_fileinfo", do_fileinfo },
  { "do_fileremove", do_fileremove },
  { "do_filerename", do_filerename },
  { "do_fileshow", do_fileshow },
  { "do_filesymlink",do_filesymlink },
  { "do_filledcontour", do_filledcontour },
  { "do_first_max", do_first_max },
  { "do_first_min", do_first_min },
  { "do_fmin", do_fmin },
  { "do_for", do_for },
  { "do_formals", do_formals },
  { "do_format", do_format },
  { "do_formatPOSIXlt", do_formatPOSIXlt },
  { "do_formatinfo", do_formatinfo },
  { "do_function", do_function },
  { "do_gc", do_gc },
  { "do_gcinfo", do_gcinfo },
  { "do_gctime", do_gctime },
  { "do_gctorture", do_gctorture },
  { "do_get", do_get },
  { "do_getNumRtoCConverters", do_getNumRtoCConverters },
  { "do_getRestart",do_getRestart },
  { "do_getRtoCConverterDescriptions", do_getRtoCConverterDescriptions },
  { "do_getRtoCConverterStatus", do_getRtoCConverterStatus },
  { "do_getSnapshot", do_getSnapshot },
  { "do_getallconnections", do_getallconnections },
  { "do_getenv", do_getenv },
  { "do_geterrmessage", do_geterrmessage },
  { "do_getlocale", do_getlocale },
  { "do_getwd", do_getwd },
  { "do_globalenv", do_globalenv },
  { "do_gray", do_gray },
  { "do_grep", do_grep },
  { "do_gsub", do_gsub },
  { "do_gzfile", do_gzfile },
  { "do_hsv", do_hsv },
  { "do_ident", do_ident },
  { "do_identify", do_identify },
  { "do_if", do_if },
  { "do_image", do_image },
  { "do_indexsearch", do_indexsearch },
  { "do_inherits", do_inherits },
  { "do_int_unzip", do_int_unzip },
  { "do_interactive", do_interactive },
  { "do_internal", do_internal },
  { "do_invisible", do_invisible },
  { "do_invokeRestart",do_invokeRestart },
  { "do_is", do_is },
  { "do_isfinite", do_isfinite },
  { "do_isincomplete", do_isincomplete },
  { "do_isinfinite", do_isinfinite },
  { "do_isloaded", do_isloaded },
  { "do_isna", do_isna },
  { "do_isnan", do_isnan },
  { "do_isopen", do_isopen },
  { "do_isseekable", do_isseekable },
  { "do_isunsorted", do_isunsorted },
  { "do_isvector", do_isvector },
  { "do_lapply", do_lapply },
  { "do_layout", do_layout },
  { "do_length", do_length },
  { "do_lengthgets", do_lengthgets },
  { "do_libfixup", do_libfixup },
  { "do_listfiles", do_listfiles },
  { "do_load", do_load },
  { "do_loadFromConn", do_loadFromConn },
  { "do_loadhistory", do_loadhistory },
  { "do_localeconv", do_localeconv },
  { "do_locator", do_locator },
  { "do_lockBnd", do_lockBnd },
  { "do_lockEnv", do_lockEnv },
  { "do_log", do_log },
  { "do_logic", do_logic },
  { "do_logic2", do_logic2 },
  { "do_logic3", do_logic3 },
  { "do_ls", do_ls },
  { "do_machine", do_machine },
  { "do_makelist", do_makelist },
  { "do_makenames", do_makenames },
  { "do_makeunique",do_makeunique },
  { "do_makevector", do_makevector },
  { "do_match", do_match },
  { "do_matchcall", do_matchcall },
  { "do_math1", do_math1 },
  { "do_math2", do_math2 },
  { "do_math3", do_math3 },
  { "do_math4", do_math4 },
  { "do_matprod", do_matprod },
  { "do_matrix", do_matrix },
  { "do_memlimits", do_memlimits },
  { "do_memoryprofile", do_memoryprofile },
  { "do_menu", do_menu },
  { "do_merge", do_merge },
  { "do_mget",do_mget },
  { "do_missing", do_missing },
  { "do_mkActiveBnd", do_mkActiveBnd },
  { "do_mkUnbound", do_mkUnbound },
  { "do_modelframe", do_modelframe },
  { "do_modelmatrix", do_modelmatrix },
  { "do_mtext", do_mtext },
  { "do_mvfft", do_mvfft },
  { "do_names", do_names },
  { "do_namesgets", do_namesgets },
  { "do_nargs", do_nargs },
  { "do_nchar", do_nchar },
  { "do_newenv", do_newenv },
  { "do_nextmethod", do_nextmethod },
  { "do_nextn", do_nextn },
  { "do_nlm", do_nlm },
  { "do_nsl", do_nsl },
  { "do_objectsize", do_objectsize },
  { "do_onexit", do_onexit },
  { "do_open", do_open },
  { "do_optim", do_optim },
  { "do_optimhess", do_optimhess },
  { "do_options", do_options },
  { "do_order", do_order },
  { "do_palette", do_palette },
  { "do_par", do_par },
  { "do_paren", do_paren },
  { "do_parentenv", do_parentenv },
  { "do_parentenvgets", do_parentenvgets },
  { "do_parentframe", do_parentframe },
  { "do_parse", do_parse },
  { "do_paste", do_paste },
  { "do_pathexpand", do_pathexpand },
  { "do_persp", do_persp },
  { "do_pgrep", do_pgrep },
  { "do_pgsub", do_pgsub },
  { "do_pipe", do_pipe },
  { "do_playDL", do_playDL },
  { "do_playSnapshot", do_playSnapshot },
  { "do_plot_new", do_plot_new },
  { "do_plot_window", do_plot_window },
  { "do_plot_xy", do_plot_xy },
  { "do_pmatch", do_pmatch },
  { "do_polygon", do_polygon },
  { "do_polyroot", do_polyroot },
  { "do_pos2env", do_pos2env },
  { "do_pregexpr", do_pregexpr },
  { "do_primitive", do_primitive },
  { "do_printdefault", do_printdefault },
  { "do_prmatrix",do_prmatrix },
  { "do_proctime", do_proctime },
  { "do_psort", do_psort },
  { "do_pushback", do_pushback },
  { "do_pushbacklength", do_pushbacklength },
  { "do_putenv", do_putenv },
  { "do_qsort", do_qsort },
  { "do_quit", do_quit },
  { "do_quote", do_quote },
  { "do_radixsort",do_radixsort },
  { "do_random1", do_random1 },
  { "do_random2", do_random2 },
  { "do_random3", do_random3 },
  { "do_range", do_range },
  { "do_rank", do_rank },
  { "do_readDCF", do_readDCF },
  { "do_readLines", do_readLines },
  { "do_readbin", do_readbin },
  { "do_readchar", do_readchar },
  { "do_readln", do_readln },
  { "do_readonlypars", do_readonlypars },
  { "do_readtablehead", do_readtablehead },
  { "do_recall", do_recall },
  { "do_rect", do_rect },
  { "do_regFinaliz", do_regFinaliz },
  { "do_regexpr", do_regexpr },
  { "do_relop", do_relop },
  { "do_remove", do_remove },
  { "do_rep", do_rep },
  { "do_repeat", do_repeat },
  { "do_replay", do_replay },
  { "do_resetCondHands",do_resetCondHands },
  { "do_restart", do_restart },
  { "do_return", do_return },
  { "do_rgb", do_rgb },
  { "do_rmultinom",do_rmultinom },
  { "do_rowscols", do_rowscols },
  { "do_sample", do_sample },
  { "do_save", do_save },
  { "do_saveToConn", do_saveToConn },
  { "do_savehistory", do_savehistory },
  { "do_scan", do_scan },
  { "do_search", do_search },
  { "do_seek", do_seek },
  { "do_segments", do_segments },
  { "do_seq", do_seq },
  { "do_serializeToConn",do_serializeToConn },
  { "do_set", do_set },
  { "do_setGPar", do_setGPar },
  { "do_setToCConverterActiveStatus", do_setToCConverterActiveStatus },
  { "do_setlocale", do_setlocale },
  { "do_setseed", do_setseed },
  { "do_setwd", do_setwd },
  { "do_signalCondition",do_signalCondition },
  { "do_sink", do_sink },
  { "do_sinknumber", do_sinknumber },
  { "do_sockconn", do_sockconn },
  { "do_sort", do_sort },
  { "do_split", do_split },
  { "do_sprintf", do_sprintf },
  { "do_standardGeneric", do_standardGeneric },
  { "do_stderr", do_stderr },
  { "do_stdin", do_stdin },
  { "do_stdout", do_stdout },
  { "do_stop", do_stop },
  { "do_strheight", do_strheight },
  { "do_strptime", do_strptime },
  { "do_strsplit", do_strsplit },
  { "do_strwidth", do_strwidth },
  { "do_subassign", do_subassign },
  { "do_subassign2", do_subassign2 },
  { "do_subassign3", do_subassign3 },
  { "do_subset", do_subset },
  { "do_subset2", do_subset2 },
  { "do_subset2_dflt", do_subset2_dflt },
  { "do_subset3", do_subset3 },
  { "do_subset_dflt", do_subset_dflt },
  { "do_substitute", do_substitute },
  { "do_substr", do_substr },
  { "do_substrgets", do_substrgets },
  { "do_sumconnection", do_sumconnection },
  { "do_summary", do_summary },
  { "do_switch", do_switch },
  { "do_symbol", do_symbol },
  { "do_symbols", do_symbols },
  { "do_sys", do_sys },
  { "do_sysgetpid",do_sysgetpid },
  { "do_sysinfo", do_sysinfo },
  { "do_syssleep", do_syssleep },
  { "do_system", do_system },
  { "do_systime", do_systime },
  { "do_tempdir", do_tempdir },
  { "do_tempfile", do_tempfile },
  { "do_termsform", do_termsform },
  { "do_text", do_text },
  { "do_textconnection", do_textconnection },
  { "do_tilde", do_tilde },
  { "do_title", do_title },
  { "do_tolower", do_tolower },
  { "do_toupper", do_toupper },
  { "do_trace", do_trace },
  { "do_transpose", do_transpose },
  { "do_truncate", do_truncate },
  { "do_typecvt", do_typecvt },
  { "do_typeof", do_typeof },
  { "do_unclass", do_unclass },
  { "do_unlist", do_unlist },
  { "do_unserializeFromConn",do_unserializeFromConn },
  { "do_unz", do_unz },
  { "do_updateform", do_updateform },
  { "do_url", do_url },
  { "do_usemethod", do_usemethod },
  { "do_version", do_version },
  { "do_warning", do_warning },
  { "do_while", do_while },
  { "do_writebin", do_writebin },
  { "do_writechar", do_writechar },
  { "do_writelines", do_writelines },
  { "do_zeroin", do_zeroin },
  {"do_bcclose",    do_bcclose},
  {"do_bcversion", do_bcversion},
  {"do_disassemble", do_disassemble},
  {"do_flush", do_flush},
  {"do_getNSRegistry",do_getNSRegistry},
  {"do_getRegNS",do_getRegNS},
  {"do_gzcon", do_gzcon},
  {"do_importIntoEnv",do_importIntoEnv},
  {"do_isNSEnv",do_isNSEnv},
  {"do_is_builtin_internal",    do_is_builtin_internal},
  {"do_loadfile", do_loadfile},
  {"do_mkcode", do_mkcode},
  {"do_putconst", do_putconst},
  {"do_regNS",do_regNS},
  {"do_savefile", do_savefile},
  {"do_sockselect", do_sockselect},
  {"do_unregNS",do_unregNS},
};

static int first_time = 1;
static int num_names;
static char **fn_names;

void
init_name_map(void)
{
  int i, j;
  int missing = 0;

  for (num_names = 0; R_FunTab[num_names].name != NULL; num_names++)
    ;
  fn_names = (char **)malloc (sizeof (char *) * num_names);
  if (fn_names == NULL) {
    fprintf (stderr, "init_name_map: Error: unable to allocate space for %d names\n", num_names);
    exit (1);
  }

  for (i = 0; i < num_names; i++) {
    fn_names[i] = NULL;
    for (j = 0; j < sizeof(name_map)/sizeof(name_map[0]); j++)
      if (name_map[j].cfun == R_FunTab[i].cfun) {
        fn_names[i] = name_map[j].name;
        break;
      }
    if (fn_names[i] == NULL) {
      fprintf (stderr, "init_name_map: Error: unable to find name for table entry %d (\"%s\", 0x%x)\n", i, R_FunTab[i].name, R_FunTab[i].cfun);
      missing++;
    }
  }
  if (missing > 0) {
      fprintf (stderr, "init_name_map: Unable to find names for %d functions. Aborting.\n", missing);
      exit (0);
  }
}

const char *get_name(int n) {
  if (first_time) {
    init_name_map ();
    first_time = 0;
  }
  if (n >= 0 && n < num_names)
    return fn_names[n];
  else {
    fprintf (stderr, "get_name: Illegal name index (%d)\n", n);
    return ("illegal_name");
  }
}

