
/* LivenessStandard.cpp
   NOTE: This file was automatically generated by DFAGen.  It is the
         implementation of the class for Liveness analysis results.
*/


#include "auto_LivenessStandard.hpp"

namespace OA {
  namespace Liveness {


LivenessDFSet::iterator LivenessStandard::getLivenessIterator(StmtHandle s) {
    LivenessDFSet::iterator retval;

    if(mLiveness[s].ptrEqual(0)) {
        mLiveness[s] = new LivenessDFSet();
    }

    retval = mLiveness[s]->begin();

    return retval;
}


LivenessDFSet::iterator LivenessStandard::getExitLivenessIterator() {
    LivenessDFSet::iterator retval;

    retval = mExitLiveness->begin();
    return retval;
}


void LivenessStandard::output(IRHandlesIRInterface& ir) {
#if 0
    sOutBuild->objStart("LivenessStandard");

    sOutBuild->mapStart("mLiveness", "StmtHandle", "OA_ptr<LocSet>");
    std::map<StmtHandle,OA_ptr<LocSet> >::iterator mapIter;
    for (mapIter = mLiveness.begin(); mapIter != mLiveness.end(); mapIter++) {
        StmtHandle s = mapIter->first;
        OA_ptr<LocSet> rdset = mapIter->second;
        if ( rdset.ptrEqual(0) ) continue;

        sOutBuild->mapEntryStart();
        sOutBuild->mapKeyStart();
        sOutBuild->outputIRHandle(s, ir);
        sOutBuild->mapKeyEnd();
        sOutBuild->mapValueStart();


        sOutBuild->listStart();
        OA_ptr<".TYPEITER."> setIter;
        setIter = getLivenessIterator(s);
        for ( ; setIter->isValid(); (*setIter)++ ) {
             sOutBuild->listItemStart(); {
             setIter->current()->output(ir);
            } sOutBuild->listItemEnd();
        }
        sOutBuild->listEnd();
        sOutBuild->mapValueEnd();
        sOutBuild->mapEntryEnd();
    }
    sOutBuild->mapEnd("mLiveness");
    sOutBuild->objEnd("LivenessStandard");
#endif
}


void LivenessStandard::dump(std::ostream& os, OA_ptr<IRHandlesIRInterface> ir)
{
    std::cout << "======Liveness===="<< std::endl;
    LivenessDFSet::iterator iter;

    std::map<StmtHandle, OA_ptr<LivenessDFSet> >::iterator mapIter;

    for (mapIter = mLiveness.begin(); mapIter != mLiveness.end(); mapIter++) {
        std::cout<< "\tstmt = " << ir->toString(mapIter->first) << std::endl;
        iter = getLivenessIterator(mapIter->first);

        for ( ; iter != mLiveness[mapIter->first]->end(); iter++ ) {
            std::cout << "\t\t";
        cout << (*iter)->toString(mIR);
            std::cout << std::endl;
        }
    }
}


  } // end of Liveness namespace
} // end of OA namespace
